name: Lab3 tests

on:
  push:
    paths:
      - 'Lab3/**'
      - '.github/workflows/lab3test.yml'
  workflow_dispatch:

jobs:
  dotnet-test:
    runs-on: [self-hosted, linux]

    defaults:
      run:
        shell: bash
        working-directory: ./Lab3

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: dotnet restore
      - name: Install tools
        run: dotnet tool restore
      - name: Run fantomas
        run: dotnet fantomas **/*.fs --check
      - name: Run fsharplint
        run: DOTNET_ROLL_FORWARD=latestMajor dotnet fsharplint lint Lab?.sln
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Run Linear
        run: cat data/linear.csv | dotnet run --no-restore --linear --step 0.7
      - name: Run Newton
        run: cat data/newton.csv | dotnet run --no-restore --newton -n 4 --step 0.5
      - name: Run Both
        run: cat data/newton.csv | dotnet run --no-restore --newton -n 4 --linear --step 0.5
